### ISSUE TITLE
Export raw data displays only "initializing export"

### ISSUE THREAD

**Issue by Vinc89** [techlib/celus#13]
Dear developers,

we have some issues when going to a platform and exporting raw data.

When I start the export only "Initializing export" is displayed and there is no progress.

Our installation is from the master branch running on Debian 10.

I haven't found any related errors in the apache logs. Do you know if some of the logs in /var/log/celery could be useful? Many thanks in advance!

**Comment by beda42** [comment]
Hi @Vinc89,

raw data export is implemented as a celery job (because it may take quite a long time). Please check that celery for celus is running correctly on your machine. It should be installed as a system service using the included ansible playbook, but maybe it did not start correctly.

**Comment by Vinc89** [comment]
Hi @beda42,

the celery service seems to be running correctly.
```
~# systemctl status celery
● celery.service - Celery Service
   Loaded: loaded (/etc/systemd/system/celery.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-07-15 13:09:07 CEST; 2 months 1 days ago
```

This is the celery.service file
```
[Unit]
Description=Celery Service
After=network.target

[Service]
Type=forking
User=celery
Group=celery
EnvironmentFile=-/etc/conf.d/celery
WorkingDirectory=/opt/celus
RuntimeDirectory=celery
RuntimeDirectoryMode=0775
ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'
ExecStop=/bin/sh -c '${CELERY_BIN} multi stopwait ${CELERYD_NODES} \
  --pidfile=${CELERYD_PID_FILE}'
ExecReload=/bin/sh -c '${CELERY_BIN} multi restart ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'

[Install]
WantedBy=multi-user.target
```

I had to modify the the service file so the service can start. I removed the line PIDFile=${CELERYD_PID_FILE}
Because the line added /run/ before the ${CELERYD_PID_FILE} and produced this error:
```
Jul 13 12:25:14 celus systemd[1]: celery.service: Can't open PID file /run/${CELERYD_PID_FILE} (yet?) after start: No such file or directory
```

If the service is running this should be no issue right?
We are running celus on Debian.
How long does the export usually take? Is there normally a progress bar visible?

**Comment by beda42** [comment]
Sorry for the late reply - I needed to try to do a fresh install using the ansible playbook to spot where the issue is.

The problem is that the exports are routed into a celery queue called `export` which the ansible playbook did not configure. It should be fixed by the latest commit in the master branch. Sorry for that.

Please try if the latest update fixes it and let me know.

**Comment by Vinc89** [comment]
Dear @beda42,
I ran the playbook with you latest commit, but unfortunately it did not fix the issue.

**Comment by beda42** [comment]
Can you please check that a worker for the `export` queue is running? There should be a separate process for this queue when you run `service celery status`.

**Comment by Vinc89** [comment]
It seems that the worker for the export queue is not running
```
celery.service - Celery Service
   Loaded: loaded (/etc/systemd/system/celery.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-10-01 14:19:28 CEST; 3 days ago
  Process: 1463 ExecStart=/bin/sh -c ${CELERY_BIN} multi start ${CELERYD_NODES}    -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE}    --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS} 
  Process: 3671 ExecReload=/bin/sh -c ${CELERY_BIN} multi restart ${CELERYD_NODES}    -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE}    --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPT
    Tasks: 11 (limit: 2355)
   Memory: 739.3M
   CGroup: /system.slice/celery.service
           ├─3680 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=2 -Q sushi --logfile=/var/log/celery/sushi.log --pidfile=/var/run/celery/sushi.pid --hostnam
           ├─3686 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=1 -Q interest --logfile=/var/log/celery/interest.log --pidfile=/var/run/celery/interest.pid 
           ├─3699 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=2 -Q sushi --logfile=/var/log/celery/sushi.log --pidfile=/var/run/celery/sushi.pid --hostnam
           ├─3700 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=1 -Q interest --logfile=/var/log/celery/interest.log --pidfile=/var/run/celery/interest.pid 
           ├─3701 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=2 -Q sushi --logfile=/var/log/celery/sushi.log --pidfile=/var/run/celery/sushi.pid --hostnam
           ├─3703 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=1 -Q import --logfile=/var/log/celery/import.log --pidfile=/var/run/celery/import.pid --host
           ├─3709 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=14400 --concurrency=1 -Q import --logfile=/var/log/celery/import.log --pidfile=/var/run/celery/import.pid --host
           ├─3714 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=300 --concurrency=3 -Ofair -Q celery --logfile=/var/log/celery/normal.log --pidfile=/var/run/celery/normal.pid -
           ├─3720 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=300 --concurrency=3 -Ofair -Q celery --logfile=/var/log/celery/normal.log --pidfile=/var/run/celery/normal.pid -
           ├─3721 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=300 --concurrency=3 -Ofair -Q celery --logfile=/var/log/celery/normal.log --pidfile=/var/run/celery/normal.pid -
           └─3722 /opt/virtualenvs/celus/bin/python -m celery worker --loglevel=debug --time-limit=300 --concurrency=3 -Ofair -Q celery
```

I verified /etc/conf.d/celery and the Q:export export option is there
```
# Extra command-line arguments to the worker
CELERYD_OPTS="--time-limit:interest=14400 --time-limit:sushi=14400 --time-limit:import=14400 --time-limit:normal=300 --time-limit:export=3600 --concurrency:interest=1 --concurrency:import=1 --concurrency:sushi=2 --concurrency:normal=3 --concurrency:export=5 -Ofair:normal -Q:normal celery -Q:interest interest -Q:sushi sushi -Q:import import -Q:export export"

```

**Comment by beda42** [comment]
That is strange. Did you restart the celery service? If yes, could you have a look into the logs, if there is something relevant? Is there a `/var/log/celery/export.log` file?

**Comment by Vinc89** [comment]
Yes, I restarted the celery service. There were no errors after the restart in /var/log/normal.log. The export just didn't show up.
```
[2021-10-05 10:42:49,177: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2021-10-05 10:42:49,178: DEBUG/MainProcess] | Worker: Building graph...
[2021-10-05 10:42:49,178: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
[2021-10-05 10:42:49,209: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2021-10-05 10:42:49,209: DEBUG/MainProcess] | Consumer: Building graph...
[2021-10-05 10:42:49,248: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Gossip, Agent, Tasks, Control, event loop}
[2021-10-05 10:42:49,278: DEBUG/MainProcess] | Worker: Starting Hub
[2021-10-05 10:42:49,278: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:49,279: DEBUG/MainProcess] | Worker: Starting Pool
[2021-10-05 10:42:50,040: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:50,058: DEBUG/MainProcess] | Worker: Starting Consumer
[2021-10-05 10:42:50,058: DEBUG/MainProcess] | Consumer: Starting Connection
[2021-10-05 10:42:50,081: INFO/MainProcess] Connected to redis://localhost:6379//
[2021-10-05 10:42:50,081: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:50,081: DEBUG/MainProcess] | Consumer: Starting Events
[2021-10-05 10:42:50,098: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:50,098: DEBUG/MainProcess] | Consumer: Starting Heart
[2021-10-05 10:42:50,101: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:50,101: DEBUG/MainProcess] | Consumer: Starting Mingle
[2021-10-05 10:42:50,101: INFO/MainProcess] mingle: searching for neighbors
[2021-10-05 10:42:51,147: INFO/MainProcess] mingle: all alone
[2021-10-05 10:42:51,147: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:51,147: DEBUG/MainProcess] | Consumer: Starting Gossip
[2021-10-05 10:42:51,151: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:51,151: DEBUG/MainProcess] | Consumer: Starting Tasks
[2021-10-05 10:42:51,157: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:51,157: DEBUG/MainProcess] | Consumer: Starting Control
[2021-10-05 10:42:51,158: DEBUG/MainProcess] ^-- substep ok
[2021-10-05 10:42:51,158: DEBUG/MainProcess] | Consumer: Starting event loop
[2021-10-05 10:42:51,159: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2021-10-05 10:42:51,159: INFO/MainProcess] normal@celus ready.
[2021-10-05 10:42:51,159: DEBUG/MainProcess] basic.qos: prefetch_count->12
[2021-10-05 10:42:51,342: DEBUG/MainProcess] pidbox received method hello(from_node='import@celus', revoked={}) [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '1200f9a3-65d7-30ab-8a25-73d94e1beed1'
} ticket:3012a13f-99db-4d56-b0e3-8b0cd2f13b73]
[2021-10-05 10:42:51,342: INFO/MainProcess] sync with import@celus
[2021-10-05 10:42:51,533: DEBUG/MainProcess] interest@celus joined the party
[2021-10-05 10:42:52,164: DEBUG/MainProcess] sushi@celus joined the party
[2021-10-05 10:42:52,356: DEBUG/MainProcess] import@celus joined the party
```

After 13 minutes this error showed up, but not sure if it's related. 
```
[2021-10-05 10:55:58,026: INFO/MainProcess] Received task: publications.tasks.erms_sync_platforms_task[fc1637df-0150-47dd-a4fa-0685313389af]  
[2021-10-05 10:55:58,029: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f68821c3ae8> (args:('publications.tasks.erms_sync_platforms_task', 'fc1637df-0150-47dd-a4fa-0685313389af', {'lang': 'py', 'task': 'publications.tasks.erms_sync_platforms_task', 'id': 'fc1637df-0150-47dd-a4fa-0685313389af', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'fc1637df-0150-47dd-a4fa-0685313389af', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen25445@celus', 'reply_to': '79f28e95-f608-38a5-8ae7-e50b6f28935e', 'correlation_id': 'fc1637df-0150-47dd-a4fa-0685313389af', 'hostname': 'normal@celus', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}, 'args': [], 'kwargs': {}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2021-10-05 10:55:58,031: INFO/MainProcess] Received task: core.tasks.erms_sync_users_and_identities_task[244466ae-634e-492f-861d-fad03626e367]  
[2021-10-05 10:55:58,031: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f68821c3ae8> (args:('core.tasks.erms_sync_users_and_identities_task', '244466ae-634e-492f-861d-fad03626e367', {'lang': 'py', 'task': 'core.tasks.erms_sync_users_and_identities_task', 'id': '244466ae-634e-492f-861d-fad03626e367', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '244466ae-634e-492f-861d-fad03626e367', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen25445@celus', 'reply_to': '79f28e95-f608-38a5-8ae7-e50b6f28935e', 'correlation_id': '244466ae-634e-492f-861d-fad03626e367', 'hostname': 'normal@celus', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}, 'args': [], 'kwargs': {}}, b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2021-10-05 10:55:58,045: DEBUG/MainProcess] Task accepted: core.tasks.erms_sync_users_and_identities_task[244466ae-634e-492f-861d-fad03626e367] pid:19820
[2021-10-05 10:55:58,047: DEBUG/MainProcess] Task accepted: publications.tasks.erms_sync_platforms_task[fc1637df-0150-47dd-a4fa-0685313389af] pid:19815
[2021-10-05 10:55:58,137: DEBUG/ForkPoolWorker-3] Starting new HTTPS connection (1): celus.ist.ac.at:443
[2021-10-05 10:55:58,153: DEBUG/ForkPoolWorker-1] Starting new HTTPS connection (1): celus.ist.ac.at:443
[2021-10-05 10:55:58,175: DEBUG/ForkPoolWorker-3] https://celus.ist.ac.at:443 "GET /api/object?class=eq.Person&order=id HTTP/1.1" 401 463
[2021-10-05 10:55:58,185: DEBUG/ForkPoolWorker-1] https://celus.ist.ac.at:443 "GET /api/object?class=eq.Platform&order=id HTTP/1.1" 401 463
[2021-10-05 10:55:58,225: ERROR/ForkPoolWorker-3] Task core.tasks.erms_sync_users_and_identities_task[244466ae-634e-492f-861d-fad03626e367] raised unexpected: OSError(101, 'Network is unreachable')
```

There is no /var/log/celery/export.log file

**Comment by beda42** [comment]
I am an idiot - I overlooked another line I had to modify to get it working :( Sorry for that.

There is a line 

```
CELERYD_NODES="normal interest sushi import"
```

which should also contain the `export` node. I pushed a change to the `master` branch which add this or you can add it manually.

**Comment by Vinc89** [comment]
And it works! Many thanks for your time and help!

By the way - I installed Celus on Debian with a few modifications to the Ansible role. If you're interested I can share the files with you.

**Comment by beda42** [comment]
No problem, you are welcome and thanks for your patience. I am sorry it took so long to solve this, and it was such a stupid error at that.

I would be definitely interested in the modifications for debian. We could somehow incorporate them into the documentation of make the playbook detect the system and adapt...
